<?php

/**
 * Here's defined paths constants
 */
const PUBLIC_IMAGES = DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR;
const VIEWS = '..' . DIRECTORY_SEPARATOR . 'app' . DIRECTORY_SEPARATOR . 'views' . DIRECTORY_SEPARATOR;
const COMMON_VIEWS = VIEWS . 'common' . DIRECTORY_SEPARATOR;
const AUTH_VIEWS = VIEWS . 'auth' . DIRECTORY_SEPARATOR;
const PAGES_VIEWS = VIEWS . 'pages' . DIRECTORY_SEPARATOR;
const TEMPLATES = VIEWS . 'templates' . DIRECTORY_SEPARATOR;
const ADMIN_LTE = DIRECTORY_SEPARATOR . 'libs' . DIRECTORY_SEPARATOR . 'adminlte' . DIRECTORY_SEPARATOR;
const ADMIN_LTE_DIST = ADMIN_LTE . 'dist' . DIRECTORY_SEPARATOR;
const ADMIN_LTE_DIST_JS = ADMIN_LTE_DIST . 'js' . DIRECTORY_SEPARATOR;
const ADMIN_LTE_DIST_CSS = ADMIN_LTE_DIST . 'css' . DIRECTORY_SEPARATOR;
const ADMIN_LTE_PLUGINS = ADMIN_LTE . 'plugins' . DIRECTORY_SEPARATOR;
const ADMIN_LTE_PLUGINS_JS = ADMIN_LTE_PLUGINS . 'js' . DIRECTORY_SEPARATOR;
const ADMIN_LTE_PLUGINS_CSS = ADMIN_LTE_PLUGINS . 'css' . DIRECTORY_SEPARATOR;
